# Generated by Django 5.2.7 on 2025-11-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher')], default='Teacher', max_length=20),
        ),
    ]
