# Generated by Django 5.2.7 on 2026-06-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingcriteria',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
