# Generated by Django 5.2.7 on 2025-10-31 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.subject'),
        ),
    ]
