# Generated by Django 5.2.7 on 2025-11-25 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_studentgrade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
