# Generated by Django 5.2.7 on 2025-11-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_studentgrade_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentgrade',
            name='unique_grade_per_student_classroom_type',
        ),
        migrations.RemoveIndex(
            model_name='studentgrade',
            name='idx_type_code',
        ),
    ]
