# Generated by Django 5.2.7 on 2026-05-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('assignments', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grading_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grades.gradingcriteria'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject'),
        ),
    ]
