# Generated by Django 5.2.7 on 2026-03-22 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='localUpdatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='syncStatus',
            field=models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('conflict', 'Conflict')], default='synced', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
