# Generated by Django 5.2.7 on 2026-06-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogtypeatendance',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='catalogtypeatendance',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
