# Generated by Django 5.2.7 on 2025-11-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='state_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='attendance.catalogtypeatendance'),
        ),
    ]
