# Generated by Django 5.2.7 on 2026-03-22 18:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='localUpdatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='syncStatus',
            field=models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('conflict', 'Conflict')], default='synced', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'CREATE EXTENSION IF NOT EXISTS "pgcrypto";',
                        'ALTER TABLE "attendances" ADD COLUMN "id_uuid" uuid;',
                        'UPDATE "attendances" SET "id_uuid" = gen_random_uuid() WHERE "id_uuid" IS NULL;',
                        'ALTER TABLE "attendances" DROP CONSTRAINT "attendances_pkey";',
                        'ALTER TABLE "attendances" DROP COLUMN "id";',
                        'ALTER TABLE "attendances" RENAME COLUMN "id_uuid" TO "id";',
                        'ALTER TABLE "attendances" ALTER COLUMN "id" SET NOT NULL;',
                        'ALTER TABLE "attendances" ADD CONSTRAINT "attendances_pkey" PRIMARY KEY ("id");',
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='attendance',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
